### ISSUE TITLE
What about AJAX?

### ISSUE THREAD

**Issue by rafikov** [EugeneDae/Magnific-Popup-History-API-Demo#1]
I've just found your extension to Magnific Popup and haven't checked the code yet. But will it be working with AJAX pages? Or I'm better to look for a different lightbox script?

**Comment by EugeneDae** [comment]
This is just a demo showing that Magnific Popup can be easily hooked up with History.js and HTML5 History API, not a complete extension. My code probably won't work with AJAX pages out of the box, but it should be easy to make it do so - look for $(document).ready calls and replace them with a "page changed" event listener.

I should note that Magnific Popup _itself_ works perfectly fine with AJAX pages as well Dmitry Semenov's other plugin PhotoSwipe, which has History API support built in.

**Comment by rafikov** [comment]
Thanks a lot Eugene. 

I'm happy with Magnific Popup but want to load some external pages and have their URL displayed correctly for bookmarking etc. It has to be mydomain.com/external.html with external.html loaded as an AJAX page.

Can it be done with Magnific/your code. Or could you recommend an alternative?

**Comment by EugeneDae** [comment]
I'm sure it can be done.

The whole code is trivial:
https://github.com/EugeneDae/Magnific-Popup-History-API-Demo/blob/gh-pages/magnific-popup.history.js

This piece reopens the popup when you load a page with the `?item=...` query:
https://github.com/EugeneDae/Magnific-Popup-History-API-Demo/blob/gh-pages/magnific-popup.open-item.js

Example: http://eugenedae.github.io/Magnific-Popup-History-API-Demo/?item=images/forest-h800.jpg

If you want this out of the box, as I said, try http://photoswipe.com/

**Comment by rafikov** [comment]
I suspect photoswipe works only with images but I want to load HTML pages. Anyways thank you. It seems I'll have to dig into the code=)
